# Generated by Django 3.2.7 on 2021-10-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Udemy_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_title', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('thumbnail', models.URLField()),
                ('what_you_will_learn', models.CharField(max_length=1000)),
                ('original_price', models.CharField(max_length=50)),
                ('coupon_code', models.CharField(max_length=50)),
                ('course_url', models.URLField(max_length=50, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='core.Category')),
            ],
        ),
    ]
